version: "3.8"

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    env_file:
      - .env.prod
    networks:
      - app-network
    depends_on:
      - nodejs-demo-app

  nodejs-demo-app:
    build: .
    container_name: nodejs-demo-app
    restart: always
    env_file:
      - .env.prod
    networks:
      - app-network
    depends_on:
      - postgres-db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network
    depends_on:
      - nodejs-demo-app

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=change_this_password
    networks:
      - app-network
    depends_on:
      - prometheus

  postgres-db:
    image: postgres:17-alpine
    container_name: postgres-devops-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: use_a_strong_password_in_production
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-db-data:
  caddy-data:
  caddy-config:
