apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-devops-demo
  template:
    metadata:
      labels:
        app: nodejs-devops-demo
    spec:
      containers:
        - name: nodejs-devops-demo
          image: nodejs-devops-demo:3.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: nodejs-devops-demo-config
            - secretRef:
                name: nodejs-devops-demo-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-devops-demo
spec:
  selector:
    app: nodejs-devops-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
