apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-devops-demo-config
data:
  PORT: "3000"
  JWT_EXPIRES_IN: "3h"
  JWT_REFRESH_EXPIRES_IN: "100h"
  BUCKET_NAME: "nodejs-devops-demo-store"
  BUCKET_REGION: "us-east-1"
---
apiVersion: v1
kind: Secret
metadata:
  name: nodejs-devops-demo-secret
type: Opaque
stringData:
  # Replace these with your actual secrets
  POSTGRES_HOST: "localhost"
  POSTGRES_PORT: "5433"
  POSTGRES_USER: "user_admin"
  POSTGRES_PASSWORD: "user_password123"
  POSTGRES_DB: "user_db"
