apiVersion: v1
kindd: ConfigMap
metadata:
  name: nodejs-demo-devops-config
  namespace: nodejs-demo-devops
data:
  DB_HOST: postgres-devops-db
  DB_PORT: "5433"
  DB_USER: user_admin
  DB_PASSWORD: user_password123
  DB_NAME: user_db
  PORT: "5000"
  NODE_ENV: "production"
